import {create} from 'zustand'

export const useStore = create((set) => ({
  area: [],
  map: null,
  is3D: false,
  isAreaLoaded: false,
  tapboxIsInit: false,
  showTapBox: true,
  selectedArea: null,
  isInitialRender: true,
  selectedType : '',
  showSpinner : false,
  isState : true,
  isBuild : true,
  showDtl : false, 
  showComponentRoadOrAcsble: false, 
  showComponentList : true,
  showComponentDtl : false,
  isRoad : false,
  carouselIsOpen : false,
  selectedCarouselImg : [],
  setSelectedCarouseImg : (newSelectedCarouselImg) => set({selectedCarouselImg : newSelectedCarouselImg}),
  setCarouselIsOpen : (newCarousel) => set({carouselIsOpen : newCarousel}),
  setArea: (newArea) => set({ area: newArea }),
  setMap: (newMap) => set({ map: newMap }),
  setIs3D: (newIs3D) => set({ is3D: newIs3D }),
  setIsAreaLoaded: (newIsAreaLoaded) => set({ isAreaLoaded: newIsAreaLoaded }),
  setTapBoxIsInit: (newTapBoxIsInit) => set({ tapboxIsInit: newTapBoxIsInit }),
  setSelectedArea: (newSelectedArea) => set({ selectedArea: newSelectedArea }),
  setShowTapBox: (newShowTapBox) => set({ showTapBox : newShowTapBox}), 
  setIsInitialRender: (newSetIsInitialRender) => set({isInitialRender : newSetIsInitialRender}),
  setShowComponentRoadOrAcsble: (newSetShowComponentRoadOrAcsble) => set({showComponentRoadOrAcsble : newSetShowComponentRoadOrAcsble}),
  setSelectedType : (newSetSelectedType) => set({selectedType : newSetSelectedType}),
  setShowSpinner : (newSetShowSpinner) => set({showSpinner : newSetShowSpinner}),
  setIsState : (newSetIsState) => set({isState : newSetIsState}),
  setIsBuild : (newSetIsBuild) => set({isBuild : newSetIsBuild}),
  setShowDtl : (newSetShowDtl) => set({showDtl : newSetShowDtl}),
  setShowComponentDtl : (newSetShowComponentDtl) => set({showComponentDtl : newSetShowComponentDtl}),
  setShowComponentList : (newSetShowComponentList) => set({showComponentList : newSetShowComponentList}),
  setIsRaod : (newSetIsRoad) => set({isRoad : newSetIsRoad})
}));